/**
 * Generated by orval v8.22.0 🍺
 * Do not edit manually.
 * Discount Analyst Dashboard
 * OpenAPI spec version: 0.1.0
 */
import { dashboardMutator } from './orval-mutator.ts';
export type AgentNameSlug = typeof AgentNameSlug[keyof typeof AgentNameSlug];


export const AgentNameSlug = {
  surveyor: 'surveyor',
  profiler: 'profiler',
  researcher: 'researcher',
  strategist: 'strategist',
  sentinel: 'sentinel',
  appraiser: 'appraiser',
  curator: 'curator',
} as const;

export type WorkflowCostFigureState = typeof WorkflowCostFigureState[keyof typeof WorkflowCostFigureState];


export const WorkflowCostFigureState = {
  amount: 'amount',
  unknown: 'unknown',
} as const;

export interface WorkflowCostFigure {
  amount_usd?: string | null;
  state: WorkflowCostFigureState;
}

export type ModelName = typeof ModelName[keyof typeof ModelName];


export const ModelName = {
  'claude-opus-4-5': 'claude-opus-4-5',
  'claude-sonnet-4-5': 'claude-sonnet-4-5',
  'claude-opus-4-6': 'claude-opus-4-6',
  'claude-sonnet-4-6': 'claude-sonnet-4-6',
  'claude-haiku-4-6': 'claude-haiku-4-6',
  'gpt-51': 'gpt-5.1',
  'gpt-52': 'gpt-5.2',
  'gpt-54': 'gpt-5.4',
  'gpt-56-luna': 'gpt-5.6-luna',
  'gpt-56-terra': 'gpt-5.6-terra',
  'gpt-6-luna': 'gpt-6-luna',
  'gpt-61-sol': 'gpt-6.1-sol',
  'gemini-3-pro-preview': 'gemini-3-pro-preview',
  'gemini-31-pro-preview': 'gemini-3.1-pro-preview',
  'deepseek-v4-flash': 'deepseek-v4-flash',
  'deepseek-v4-pro': 'deepseek-v4-pro',
} as const;

export type ExecutionStatusApi = typeof ExecutionStatusApi[keyof typeof ExecutionStatusApi];


export const ExecutionStatusApi = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  skipped: 'skipped',
  rejected: 'rejected',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export interface AgentExecutionSummary {
  agent_name: AgentNameSlug;
  completed_at: string | null;
  cost: WorkflowCostFigure;
  id: string;
  model_name?: ModelName | null;
  started_at: string | null;
  status: ExecutionStatusApi;
}

export interface AgentTypeCost {
  agent_name: AgentNameSlug;
  cost: WorkflowCostFigure;
}

export type RebalanceAction = typeof RebalanceAction[keyof typeof RebalanceAction];


export const RebalanceAction = {
  enter: 'enter',
  increase: 'increase',
  hold: 'hold',
  reduce: 'reduce',
  exit: 'exit',
  avoid: 'avoid',
} as const;

export interface AllocationPosition {
  /**
     * @minimum 0
     * @maximum 100
     */
  acceptable_weight_high_pct: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  acceptable_weight_low_pct: number;
  action: RebalanceAction;
  company_name: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  current_weight_pct: number;
  is_existing_position: boolean;
  rationale: string;
  source_run_id: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  target_weight_pct: number;
  ticker: string;
}

export type CandidateGateStatusApi = typeof CandidateGateStatusApi[keyof typeof CandidateGateStatusApi];


export const CandidateGateStatusApi = {
  passed: 'passed',
  rejected: 'rejected',
} as const;

export interface CandidateGateSummary {
  gate_failure_reason: string | null;
  gate_status: CandidateGateStatusApi | null;
  is_actively_trading: boolean | null;
  resolved_ticker: string | null;
  source_ticker: string;
}

export interface CashAllocation {
  /**
     * @minimum 0
     * @maximum 100
     */
  acceptable_weight_high_pct: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  acceptable_weight_low_pct: number;
  /**
     * @minimum 0
     * @maximum 100
     */
  current_weight_pct: number;
  rationale: string;
  /**
     * @minimum 0
     * @maximum 100
     */
  target_weight_pct: number;
}

export interface ConversationResponse {
  assistant_response: string;
  messages_json: string;
  system_prompt: string;
}

export interface PortfolioPositionInput {
  /** @minLength 1 */
  ticker: string;
  /** @minimum 0 */
  value_gbp: number;
}

export interface CreateWorkflowRunRequest {
  /** @minimum 0 */
  cash_gbp: number;
  is_mock?: boolean;
  positions?: PortfolioPositionInput[];
  suggestion_tickers?: string[];
}

export interface ProfilerRunCreated {
  run_id: string;
  ticker: string;
}

export interface CreateWorkflowRunResponse {
  profiler_runs: ProfilerRunCreated[];
  surveyor_started?: boolean;
  workflow_run_id: string;
}

export interface YfinanceFreshnessResponse {
  installed_version: string;
  is_outdated: boolean;
  latest_version: string | null;
}

export interface DashboardStatusResponse {
  companies_house_cache_present: boolean;
  sec_user_agent_configured: boolean;
  yfinance: YfinanceFreshnessResponse;
}

export type DecisionTypeApi = typeof DecisionTypeApi[keyof typeof DecisionTypeApi];


export const DecisionTypeApi = {
  rating_table: 'rating_table',
  sentinel_rejection: 'sentinel_rejection',
  data_quality_rejection: 'data_quality_rejection',
  appraised: 'appraised',
} as const;

export type EntryPathApi = typeof EntryPathApi[keyof typeof EntryPathApi];


export const EntryPathApi = {
  surveyor: 'surveyor',
  profiler: 'profiler',
} as const;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: (string | number)[];
  msg: string;
  type: string;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface SharedRiskCluster {
  allocation_effect: string;
  label: string;
  mechanism: string;
  member_tickers: string[];
}

export interface PortfolioAllocation {
  allocation_date: string;
  cash: CashAllocation;
  portfolio_rationale: string;
  positions: AllocationPosition[];
  shared_risk_clusters: SharedRiskCluster[];
}

export interface PortfolioResponse {
  /** @minimum 0 */
  cash_gbp: number;
  positions: PortfolioPositionInput[];
  suggestion_tickers: string[];
}

export type TickerRunStatusApi = typeof TickerRunStatusApi[keyof typeof TickerRunStatusApi];


export const TickerRunStatusApi = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export interface TickerRunDetail {
  agent_executions: AgentExecutionSummary[];
  candidate_gate?: CandidateGateSummary | null;
  company_name: string;
  decision_type: DecisionTypeApi | null;
  entry_path: EntryPathApi;
  final_rating: string | null;
  id: string;
  status: TickerRunStatusApi;
  ticker: string;
}

export type WorkflowRunStatusApi = typeof WorkflowRunStatusApi[keyof typeof WorkflowRunStatusApi];


export const WorkflowRunStatusApi = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export interface WorkflowRunDetailResponse {
  can_retry_failed_agents: boolean;
  completed_at: string | null;
  cost_by_agent: AgentTypeCost[];
  cost_successful: WorkflowCostFigure;
  cost_total: WorkflowCostFigure;
  cost_unsuccessful: WorkflowCostFigure;
  curator_execution: AgentExecutionSummary | null;
  error_message: string | null;
  id: string;
  is_mock: boolean;
  portfolio_value_gbp: number | null;
  runs: TickerRunDetail[];
  started_at: string;
  status: WorkflowRunStatusApi;
  surveyor_execution: AgentExecutionSummary | null;
}

export interface WorkflowRunListItem {
  completed_at: string | null;
  completed_ticker_run_count: number;
  error_message: string | null;
  failed_ticker_run_count: number;
  id: string;
  is_mock: boolean;
  started_at: string;
  status: WorkflowRunStatusApi;
  ticker_run_count: number;
}

export type WorkflowScopedAgentNameSlug = typeof WorkflowScopedAgentNameSlug[keyof typeof WorkflowScopedAgentNameSlug];


export const WorkflowScopedAgentNameSlug = {
  surveyor: 'surveyor',
  curator: 'curator',
} as const;

export const getGetRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGetUrl = (runId: string,
    agentName: AgentNameSlug,) => {




  return `/api/agents/runs/${runId}/agents/${agentName}/conversation`
}

/**
 * @summary Get Run Agent Conversation
 */
export const getRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGet = async (runId: string,
    agentName: AgentNameSlug, options?: RequestInit): Promise<ConversationResponse> => {

  return dashboardMutator<ConversationResponse>(getGetRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGetUrl(runId,agentName),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetWorkflowAgentConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsWorkflowAgentNameConversationGetUrl = (workflowRunId: string,
    workflowAgentName: WorkflowScopedAgentNameSlug,) => {




  return `/api/agents/workflow_runs/${workflowRunId}/agents/${workflowAgentName}/conversation`
}

/**
 * @summary Get Workflow Agent Conversation
 */
export const getWorkflowAgentConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsWorkflowAgentNameConversationGet = async (workflowRunId: string,
    workflowAgentName: WorkflowScopedAgentNameSlug, options?: RequestInit): Promise<ConversationResponse> => {

  return dashboardMutator<ConversationResponse>(getGetWorkflowAgentConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsWorkflowAgentNameConversationGetUrl(workflowRunId,workflowAgentName),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetPortfolioApiPortfolioGetUrl = () => {




  return `/api/portfolio`
}

/**
 * @summary Get Portfolio
 */
export const getPortfolioApiPortfolioGet = async ( options?: RequestInit): Promise<PortfolioResponse> => {

  return dashboardMutator<PortfolioResponse>(getGetPortfolioApiPortfolioGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetDashboardStatusApiStatusGetUrl = () => {




  return `/api/status`
}

/**
 * @summary Get Dashboard Status
 */
export const getDashboardStatusApiStatusGet = async ( options?: RequestInit): Promise<DashboardStatusResponse> => {

  return dashboardMutator<DashboardStatusResponse>(getGetDashboardStatusApiStatusGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getListWorkflowRunsApiWorkflowRunsGetUrl = () => {




  return `/api/workflow_runs`
}

/**
 * @summary List Workflow Runs
 */
export const listWorkflowRunsApiWorkflowRunsGet = async ( options?: RequestInit): Promise<WorkflowRunListItem[]> => {

  return dashboardMutator<WorkflowRunListItem[]>(getListWorkflowRunsApiWorkflowRunsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCreateWorkflowRunApiWorkflowRunsPostUrl = () => {




  return `/api/workflow_runs`
}

/**
 * @summary Create Workflow Run
 */
export const createWorkflowRunApiWorkflowRunsPost = async (createWorkflowRunRequest: CreateWorkflowRunRequest, options?: RequestInit): Promise<CreateWorkflowRunResponse> => {

  return dashboardMutator<CreateWorkflowRunResponse>(getCreateWorkflowRunApiWorkflowRunsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createWorkflowRunRequest)
  }
);}



export const getDeleteWorkflowRunApiWorkflowRunsWorkflowRunIdDeleteUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}`
}

/**
 * @summary Delete Workflow Run
 */
export const deleteWorkflowRunApiWorkflowRunsWorkflowRunIdDelete = async (workflowRunId: string, options?: RequestInit): Promise<void> => {

  return dashboardMutator<void>(getDeleteWorkflowRunApiWorkflowRunsWorkflowRunIdDeleteUrl(workflowRunId),
  {
    ...options,
    method: 'DELETE'


  }
);}



export const getGetWorkflowRunApiWorkflowRunsWorkflowRunIdGetUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}`
}

/**
 * @summary Get Workflow Run
 */
export const getWorkflowRunApiWorkflowRunsWorkflowRunIdGet = async (workflowRunId: string, options?: RequestInit): Promise<WorkflowRunDetailResponse> => {

  return dashboardMutator<WorkflowRunDetailResponse>(getGetWorkflowRunApiWorkflowRunsWorkflowRunIdGetUrl(workflowRunId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getGetWorkflowAllocationApiWorkflowRunsWorkflowRunIdAllocationGetUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}/allocation`
}

/**
 * @summary Get Workflow Allocation
 */
export const getWorkflowAllocationApiWorkflowRunsWorkflowRunIdAllocationGet = async (workflowRunId: string, options?: RequestInit): Promise<PortfolioAllocation> => {

  return dashboardMutator<PortfolioAllocation>(getGetWorkflowAllocationApiWorkflowRunsWorkflowRunIdAllocationGetUrl(workflowRunId),
  {
    ...options,
    method: 'GET'


  }
);}



export const getCancelWorkflowRunApiWorkflowRunsWorkflowRunIdCancelPostUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}/cancel`
}

/**
 * @summary Cancel Workflow Run
 */
export const cancelWorkflowRunApiWorkflowRunsWorkflowRunIdCancelPost = async (workflowRunId: string, options?: RequestInit): Promise<void> => {

  return dashboardMutator<void>(getCancelWorkflowRunApiWorkflowRunsWorkflowRunIdCancelPostUrl(workflowRunId),
  {
    ...options,
    method: 'POST'


  }
);}



export const getRetryFailedAgentsApiWorkflowRunsWorkflowRunIdRetryFailedAgentsPostUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}/retry_failed_agents`
}

/**
 * @summary Retry Failed Agents
 */
export const retryFailedAgentsApiWorkflowRunsWorkflowRunIdRetryFailedAgentsPost = async (workflowRunId: string, options?: RequestInit): Promise<unknown> => {

  return dashboardMutator<unknown>(getRetryFailedAgentsApiWorkflowRunsWorkflowRunIdRetryFailedAgentsPostUrl(workflowRunId),
  {
    ...options,
    method: 'POST'


  }
);}
