/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Discount Analyst Dashboard
 * OpenAPI spec version: 0.1.0
 */
import { dashboardMutator } from './orval-mutator';
export type AgentExecutionSummaryCompletedAt = string | null;

export type AgentExecutionSummaryModelName = ModelName | null;

export type AgentExecutionSummaryStartedAt = string | null;

export interface AgentExecutionSummary {
  agent_name: AgentNameSlug;
  completed_at: AgentExecutionSummaryCompletedAt;
  id: string;
  model_name?: AgentExecutionSummaryModelName;
  started_at: AgentExecutionSummaryStartedAt;
  status: ExecutionStatusApi;
}

export type AgentNameSlug = typeof AgentNameSlug[keyof typeof AgentNameSlug];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentNameSlug = {
  surveyor: 'surveyor',
  profiler: 'profiler',
  researcher: 'researcher',
  strategist: 'strategist',
  sentinel: 'sentinel',
  appraiser: 'appraiser',
  allocator: 'allocator',
} as const;

export type AllocationPositionPolicy = InvestablePolicy | RetainOrReducePolicy | ForcedZeroPolicy;

export interface AllocationPosition {
  /**
   * @minimum 0
   * @maximum 100
   */
  acceptable_weight_high_pct: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  acceptable_weight_low_pct: number;
  action: RebalanceAction;
  company_name: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  current_weight_pct: number;
  is_existing_position: boolean;
  policy: AllocationPositionPolicy;
  rationale: string;
  source_run_id: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  target_weight_pct: number;
  ticker: string;
}

export type CandidateGateStatusApi = typeof CandidateGateStatusApi[keyof typeof CandidateGateStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CandidateGateStatusApi = {
  passed: 'passed',
  rejected: 'rejected',
} as const;

export type CandidateGateSummaryGateFailureReason = string | null;

export type CandidateGateSummaryGateStatus = CandidateGateStatusApi | null;

export type CandidateGateSummaryIsActivelyTrading = boolean | null;

export type CandidateGateSummaryResolvedTicker = string | null;

export interface CandidateGateSummary {
  gate_failure_reason: CandidateGateSummaryGateFailureReason;
  gate_status: CandidateGateSummaryGateStatus;
  is_actively_trading: CandidateGateSummaryIsActivelyTrading;
  resolved_ticker: CandidateGateSummaryResolvedTicker;
  source_ticker: string;
}

export interface CashAllocation {
  /**
   * @minimum 0
   * @maximum 100
   */
  acceptable_weight_high_pct: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  acceptable_weight_low_pct: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  current_weight_pct: number;
  rationale: string;
  /**
   * @minimum 0
   * @maximum 100
   */
  target_weight_pct: number;
}

export interface ConversationResponse {
  assistant_response: string;
  messages_json: string;
  system_prompt: string;
}

export interface CreateWorkflowRunRequest {
  is_mock?: boolean;
  /** @minItems 0 */
  portfolio_tickers: string[];
}

export interface CreateWorkflowRunResponse {
  profiler_runs: ProfilerRunCreated[];
  surveyor_started?: boolean;
  workflow_run_id: string;
}

export interface DashboardStatusResponse {
  yfinance: YfinanceFreshnessResponse;
}

export type DecisionTypeApi = typeof DecisionTypeApi[keyof typeof DecisionTypeApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DecisionTypeApi = {
  rating_table: 'rating_table',
  sentinel_rejection: 'sentinel_rejection',
  data_quality_rejection: 'data_quality_rejection',
} as const;

export type EntryPathApi = typeof EntryPathApi[keyof typeof EntryPathApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryPathApi = {
  surveyor: 'surveyor',
  profiler: 'profiler',
} as const;

export type ExecutionStatusApi = typeof ExecutionStatusApi[keyof typeof ExecutionStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExecutionStatusApi = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  skipped: 'skipped',
  rejected: 'rejected',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export interface ForcedZeroPolicy {
  kind?: 'forced_zero';
  reason: ForcedZeroReason;
}

export type ForcedZeroReason = typeof ForcedZeroReason[keyof typeof ForcedZeroReason];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ForcedZeroReason = {
  new_hold: 'new_hold',
  sell: 'sell',
  strong_sell: 'strong_sell',
} as const;

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export const InvestablePolicyValue = {
  kind: 'investable',
} as const;
export type InvestablePolicy = typeof InvestablePolicyValue;

export type ModelName = typeof ModelName[keyof typeof ModelName];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelName = {
  'claude-opus-4-5': 'claude-opus-4-5',
  'claude-sonnet-4-5': 'claude-sonnet-4-5',
  'claude-opus-4-6': 'claude-opus-4-6',
  'claude-sonnet-4-6': 'claude-sonnet-4-6',
  'claude-haiku-4-6': 'claude-haiku-4-6',
  'gpt-51': 'gpt-5.1',
  'gpt-52': 'gpt-5.2',
  'gpt-54': 'gpt-5.4',
  'gpt-56-luna': 'gpt-5.6-luna',
  'gemini-3-pro-preview': 'gemini-3-pro-preview',
  'gemini-31-pro-preview': 'gemini-3.1-pro-preview',
  'deepseek-v4-flash': 'deepseek-v4-flash',
  'deepseek-v4-pro': 'deepseek-v4-pro',
} as const;

export interface PortfolioAllocation {
  allocation_date: string;
  cash: CashAllocation;
  portfolio_rationale: string;
  positions: AllocationPosition[];
  shared_risk_clusters: SharedRiskCluster[];
}

export interface PortfolioResponse {
  portfolio_tickers: string[];
}

export interface ProfilerRunCreated {
  run_id: string;
  ticker: string;
}

export type RebalanceAction = typeof RebalanceAction[keyof typeof RebalanceAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RebalanceAction = {
  enter: 'enter',
  increase: 'increase',
  hold: 'hold',
  reduce: 'reduce',
  exit: 'exit',
  avoid: 'avoid',
} as const;

export interface RetainOrReducePolicy {
  /**
   * @minimum 0
   * @maximum 100
   */
  current_weight_pct: number;
  kind?: 'retain_or_reduce';
}

export interface SharedRiskCluster {
  allocation_effect: string;
  label: string;
  mechanism: string;
  member_tickers: string[];
}

export type TickerRunDetailCandidateGate = CandidateGateSummary | null;

export type TickerRunDetailDecisionType = DecisionTypeApi | null;

export type TickerRunDetailFinalRating = string | null;

export interface TickerRunDetail {
  agent_executions: AgentExecutionSummary[];
  candidate_gate?: TickerRunDetailCandidateGate;
  company_name: string;
  decision_type: TickerRunDetailDecisionType;
  entry_path: EntryPathApi;
  final_rating: TickerRunDetailFinalRating;
  id: string;
  status: TickerRunStatusApi;
  ticker: string;
}

export type TickerRunStatusApi = typeof TickerRunStatusApi[keyof typeof TickerRunStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TickerRunStatusApi = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export type ValidationErrorCtx = { [key: string]: unknown };

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type WorkflowRunDetailResponseAllocatorExecution = AgentExecutionSummary | null;

export type WorkflowRunDetailResponseCompletedAt = string | null;

export type WorkflowRunDetailResponseErrorMessage = string | null;

export type WorkflowRunDetailResponseSurveyorExecution = AgentExecutionSummary | null;

export interface WorkflowRunDetailResponse {
  allocator_execution: WorkflowRunDetailResponseAllocatorExecution;
  can_retry_failed_agents: boolean;
  completed_at: WorkflowRunDetailResponseCompletedAt;
  error_message: WorkflowRunDetailResponseErrorMessage;
  id: string;
  is_mock: boolean;
  runs: TickerRunDetail[];
  started_at: string;
  status: WorkflowRunStatusApi;
  surveyor_execution: WorkflowRunDetailResponseSurveyorExecution;
}

export type WorkflowRunListItemCompletedAt = string | null;

export type WorkflowRunListItemErrorMessage = string | null;

export interface WorkflowRunListItem {
  completed_at: WorkflowRunListItemCompletedAt;
  completed_ticker_run_count: number;
  error_message: WorkflowRunListItemErrorMessage;
  failed_ticker_run_count: number;
  id: string;
  is_mock: boolean;
  started_at: string;
  status: WorkflowRunStatusApi;
  ticker_run_count: number;
}

export type WorkflowRunStatusApi = typeof WorkflowRunStatusApi[keyof typeof WorkflowRunStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowRunStatusApi = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
  cancelled: 'cancelled',
} as const;

export type WorkflowScopedAgentNameSlug = typeof WorkflowScopedAgentNameSlug[keyof typeof WorkflowScopedAgentNameSlug];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowScopedAgentNameSlug = {
  surveyor: 'surveyor',
  allocator: 'allocator',
} as const;

export type YfinanceFreshnessResponseLatestVersion = string | null;

export interface YfinanceFreshnessResponse {
  installed_version: string;
  is_outdated: boolean;
  latest_version: YfinanceFreshnessResponseLatestVersion;
}

/**
 * @summary Get Run Agent Conversation
 */
export const getGetRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGetUrl = (runId: string,
    agentName: AgentNameSlug,) => {


  

  return `/api/agents/runs/${runId}/agents/${agentName}/conversation`
}

export const getRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGet = async (runId: string,
    agentName: AgentNameSlug, options?: RequestInit): Promise<ConversationResponse> => {
  
  return dashboardMutator<ConversationResponse>(getGetRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGetUrl(runId,agentName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get Workflow Agent Conversation
 */
export const getGetWorkflowAgentConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsWorkflowAgentNameConversationGetUrl = (workflowRunId: string,
    workflowAgentName: WorkflowScopedAgentNameSlug,) => {


  

  return `/api/agents/workflow_runs/${workflowRunId}/agents/${workflowAgentName}/conversation`
}

export const getWorkflowAgentConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsWorkflowAgentNameConversationGet = async (workflowRunId: string,
    workflowAgentName: WorkflowScopedAgentNameSlug, options?: RequestInit): Promise<ConversationResponse> => {
  
  return dashboardMutator<ConversationResponse>(getGetWorkflowAgentConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsWorkflowAgentNameConversationGetUrl(workflowRunId,workflowAgentName),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get Portfolio
 */
export const getGetPortfolioApiPortfolioGetUrl = () => {


  

  return `/api/portfolio`
}

export const getPortfolioApiPortfolioGet = async ( options?: RequestInit): Promise<PortfolioResponse> => {
  
  return dashboardMutator<PortfolioResponse>(getGetPortfolioApiPortfolioGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get Dashboard Status
 */
export const getGetDashboardStatusApiStatusGetUrl = () => {


  

  return `/api/status`
}

export const getDashboardStatusApiStatusGet = async ( options?: RequestInit): Promise<DashboardStatusResponse> => {
  
  return dashboardMutator<DashboardStatusResponse>(getGetDashboardStatusApiStatusGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary List Workflow Runs
 */
export const getListWorkflowRunsApiWorkflowRunsGetUrl = () => {


  

  return `/api/workflow_runs`
}

export const listWorkflowRunsApiWorkflowRunsGet = async ( options?: RequestInit): Promise<WorkflowRunListItem[]> => {
  
  return dashboardMutator<WorkflowRunListItem[]>(getListWorkflowRunsApiWorkflowRunsGetUrl(),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Create Workflow Run
 */
export const getCreateWorkflowRunApiWorkflowRunsPostUrl = () => {


  

  return `/api/workflow_runs`
}

export const createWorkflowRunApiWorkflowRunsPost = async (createWorkflowRunRequest: CreateWorkflowRunRequest, options?: RequestInit): Promise<CreateWorkflowRunResponse> => {
  
  return dashboardMutator<CreateWorkflowRunResponse>(getCreateWorkflowRunApiWorkflowRunsPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkflowRunRequest,)
  }
);}



/**
 * @summary Delete Workflow Run
 */
export const getDeleteWorkflowRunApiWorkflowRunsWorkflowRunIdDeleteUrl = (workflowRunId: string,) => {


  

  return `/api/workflow_runs/${workflowRunId}`
}

export const deleteWorkflowRunApiWorkflowRunsWorkflowRunIdDelete = async (workflowRunId: string, options?: RequestInit): Promise<void> => {
  
  return dashboardMutator<void>(getDeleteWorkflowRunApiWorkflowRunsWorkflowRunIdDeleteUrl(workflowRunId),
  {      
    ...options,
    method: 'DELETE'
    
    
  }
);}



/**
 * @summary Get Workflow Run
 */
export const getGetWorkflowRunApiWorkflowRunsWorkflowRunIdGetUrl = (workflowRunId: string,) => {


  

  return `/api/workflow_runs/${workflowRunId}`
}

export const getWorkflowRunApiWorkflowRunsWorkflowRunIdGet = async (workflowRunId: string, options?: RequestInit): Promise<WorkflowRunDetailResponse> => {
  
  return dashboardMutator<WorkflowRunDetailResponse>(getGetWorkflowRunApiWorkflowRunsWorkflowRunIdGetUrl(workflowRunId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Get Workflow Allocation
 */
export const getGetWorkflowAllocationApiWorkflowRunsWorkflowRunIdAllocationGetUrl = (workflowRunId: string,) => {


  

  return `/api/workflow_runs/${workflowRunId}/allocation`
}

export const getWorkflowAllocationApiWorkflowRunsWorkflowRunIdAllocationGet = async (workflowRunId: string, options?: RequestInit): Promise<PortfolioAllocation> => {
  
  return dashboardMutator<PortfolioAllocation>(getGetWorkflowAllocationApiWorkflowRunsWorkflowRunIdAllocationGetUrl(workflowRunId),
  {      
    ...options,
    method: 'GET'
    
    
  }
);}



/**
 * @summary Cancel Workflow Run
 */
export const getCancelWorkflowRunApiWorkflowRunsWorkflowRunIdCancelPostUrl = (workflowRunId: string,) => {


  

  return `/api/workflow_runs/${workflowRunId}/cancel`
}

export const cancelWorkflowRunApiWorkflowRunsWorkflowRunIdCancelPost = async (workflowRunId: string, options?: RequestInit): Promise<void> => {
  
  return dashboardMutator<void>(getCancelWorkflowRunApiWorkflowRunsWorkflowRunIdCancelPostUrl(workflowRunId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}



/**
 * @summary Retry Failed Agents
 */
export const getRetryFailedAgentsApiWorkflowRunsWorkflowRunIdRetryFailedAgentsPostUrl = (workflowRunId: string,) => {


  

  return `/api/workflow_runs/${workflowRunId}/retry_failed_agents`
}

export const retryFailedAgentsApiWorkflowRunsWorkflowRunIdRetryFailedAgentsPost = async (workflowRunId: string, options?: RequestInit): Promise<unknown> => {
  
  return dashboardMutator<unknown>(getRetryFailedAgentsApiWorkflowRunsWorkflowRunIdRetryFailedAgentsPostUrl(workflowRunId),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
