/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Discount Analyst Dashboard
 * OpenAPI spec version: 0.1.0
 */
import { dashboardMutator } from './orval-mutator';
export type AgentExecutionSummaryCompletedAt = string | null;

export type AgentExecutionSummaryStartedAt = string | null;

export interface AgentExecutionSummary {
  agent_name: AgentNameSlug;
  completed_at: AgentExecutionSummaryCompletedAt;
  id: string;
  started_at: AgentExecutionSummaryStartedAt;
  status: ExecutionStatusApi;
}

export type AgentNameSlug = typeof AgentNameSlug[keyof typeof AgentNameSlug];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AgentNameSlug = {
  surveyor: 'surveyor',
  profiler: 'profiler',
  researcher: 'researcher',
  strategist: 'strategist',
  sentinel: 'sentinel',
  appraiser: 'appraiser',
  arbiter: 'arbiter',
} as const;

export interface ConversationResponse {
  assistant_response: string;
  messages_json: string;
  system_prompt: string;
}

export interface CreateWorkflowRunRequest {
  is_mock?: boolean;
  /** @minItems 0 */
  portfolio_tickers: string[];
}

export interface CreateWorkflowRunResponse {
  profiler_runs: ProfilerRunCreated[];
  surveyor_started?: boolean;
  workflow_run_id: string;
}

export type DecisionTypeApi = typeof DecisionTypeApi[keyof typeof DecisionTypeApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DecisionTypeApi = {
  arbiter: 'arbiter',
  sentinel_rejection: 'sentinel_rejection',
} as const;

export type EntryPathApi = typeof EntryPathApi[keyof typeof EntryPathApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EntryPathApi = {
  surveyor: 'surveyor',
  profiler: 'profiler',
} as const;

export type ExecutionStatusApi = typeof ExecutionStatusApi[keyof typeof ExecutionStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ExecutionStatusApi = {
  pending: 'pending',
  running: 'running',
  completed: 'completed',
  skipped: 'skipped',
  rejected: 'rejected',
  failed: 'failed',
} as const;

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PortfolioResponse {
  portfolio_tickers: string[];
}

export interface ProfilerRunCreated {
  run_id: string;
  ticker: string;
}

export type SurveyorExecutionSummaryCompletedAt = string | null;

export type SurveyorExecutionSummaryStartedAt = string | null;

export interface SurveyorExecutionSummary {
  agent_name: AgentNameSlug;
  completed_at: SurveyorExecutionSummaryCompletedAt;
  id: string;
  started_at: SurveyorExecutionSummaryStartedAt;
  status: ExecutionStatusApi;
}

export type TickerRunDetailDecisionType = DecisionTypeApi | null;

export type TickerRunDetailFinalRating = string | null;

export interface TickerRunDetail {
  agent_executions: AgentExecutionSummary[];
  company_name: string;
  decision_type: TickerRunDetailDecisionType;
  entry_path: EntryPathApi;
  final_rating: TickerRunDetailFinalRating;
  id: string;
  status: TickerRunStatusApi;
  ticker: string;
}

export type TickerRunStatusApi = typeof TickerRunStatusApi[keyof typeof TickerRunStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TickerRunStatusApi = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
} as const;

export type ValidationErrorCtx = { [key: string]: unknown };

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
  ctx?: ValidationErrorCtx;
  input?: unknown;
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
}

export type WorkflowRunDetailResponseCompletedAt = string | null;

export type WorkflowRunDetailResponseErrorMessage = string | null;

export type WorkflowRunDetailResponseSurveyorExecution = SurveyorExecutionSummary | null;

export interface WorkflowRunDetailResponse {
  completed_at: WorkflowRunDetailResponseCompletedAt;
  error_message: WorkflowRunDetailResponseErrorMessage;
  id: string;
  is_mock: boolean;
  runs: TickerRunDetail[];
  started_at: string;
  status: WorkflowRunStatusApi;
  surveyor_execution: WorkflowRunDetailResponseSurveyorExecution;
}

export type WorkflowRunListItemCompletedAt = string | null;

export type WorkflowRunListItemErrorMessage = string | null;

export interface WorkflowRunListItem {
  completed_at: WorkflowRunListItemCompletedAt;
  completed_ticker_run_count: number;
  error_message: WorkflowRunListItemErrorMessage;
  failed_ticker_run_count: number;
  id: string;
  is_mock: boolean;
  started_at: string;
  status: WorkflowRunStatusApi;
  ticker_run_count: number;
}

export type WorkflowRunStatusApi = typeof WorkflowRunStatusApi[keyof typeof WorkflowRunStatusApi];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WorkflowRunStatusApi = {
  running: 'running',
  completed: 'completed',
  failed: 'failed',
} as const;

/**
 * @summary Get Run Agent Conversation
 */
export const getGetRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGetUrl = (runId: string,
    agentName: AgentNameSlug,) => {




  return `/api/agents/runs/${runId}/agents/${agentName}/conversation`
}

export const getRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGet = async (runId: string,
    agentName: AgentNameSlug, options?: RequestInit): Promise<ConversationResponse> => {

  return dashboardMutator<ConversationResponse>(getGetRunAgentConversationApiAgentsRunsRunIdAgentsAgentNameConversationGetUrl(runId,agentName),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Get Surveyor Conversation
 */
export const getGetSurveyorConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsSurveyorConversationGetUrl = (workflowRunId: string,) => {




  return `/api/agents/workflow_runs/${workflowRunId}/agents/surveyor/conversation`
}

export const getSurveyorConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsSurveyorConversationGet = async (workflowRunId: string, options?: RequestInit): Promise<ConversationResponse> => {

  return dashboardMutator<ConversationResponse>(getGetSurveyorConversationApiAgentsWorkflowRunsWorkflowRunIdAgentsSurveyorConversationGetUrl(workflowRunId),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Get Portfolio
 */
export const getGetPortfolioApiPortfolioGetUrl = () => {




  return `/api/portfolio`
}

export const getPortfolioApiPortfolioGet = async ( options?: RequestInit): Promise<PortfolioResponse> => {

  return dashboardMutator<PortfolioResponse>(getGetPortfolioApiPortfolioGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary List Workflow Runs
 */
export const getListWorkflowRunsApiWorkflowRunsGetUrl = () => {




  return `/api/workflow_runs`
}

export const listWorkflowRunsApiWorkflowRunsGet = async ( options?: RequestInit): Promise<WorkflowRunListItem[]> => {

  return dashboardMutator<WorkflowRunListItem[]>(getListWorkflowRunsApiWorkflowRunsGetUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



/**
 * @summary Create Workflow Run
 */
export const getCreateWorkflowRunApiWorkflowRunsPostUrl = () => {




  return `/api/workflow_runs`
}

export const createWorkflowRunApiWorkflowRunsPost = async (createWorkflowRunRequest: CreateWorkflowRunRequest, options?: RequestInit): Promise<CreateWorkflowRunResponse> => {

  return dashboardMutator<CreateWorkflowRunResponse>(getCreateWorkflowRunApiWorkflowRunsPostUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      createWorkflowRunRequest,)
  }
);}



/**
 * @summary Delete Workflow Run
 */
export const getDeleteWorkflowRunApiWorkflowRunsWorkflowRunIdDeleteUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}`
}

export const deleteWorkflowRunApiWorkflowRunsWorkflowRunIdDelete = async (workflowRunId: string, options?: RequestInit): Promise<void> => {

  return dashboardMutator<void>(getDeleteWorkflowRunApiWorkflowRunsWorkflowRunIdDeleteUrl(workflowRunId),
  {
    ...options,
    method: 'DELETE'


  }
);}



/**
 * @summary Get Workflow Run
 */
export const getGetWorkflowRunApiWorkflowRunsWorkflowRunIdGetUrl = (workflowRunId: string,) => {




  return `/api/workflow_runs/${workflowRunId}`
}

export const getWorkflowRunApiWorkflowRunsWorkflowRunIdGet = async (workflowRunId: string, options?: RequestInit): Promise<WorkflowRunDetailResponse> => {

  return dashboardMutator<WorkflowRunDetailResponse>(getGetWorkflowRunApiWorkflowRunsWorkflowRunIdGetUrl(workflowRunId),
  {
    ...options,
    method: 'GET'


  }
);}
