from enum import StrEnum


class AgentName(StrEnum):
    APPRAISER = "APPRAISER"
    ARBITER = "ARBITER"
    RESEARCHER = "RESEARCHER"
    SENTINEL = "SENTINEL"
    STRATEGIST = "STRATEGIST"
    SURVEYOR = "SURVEYOR"
