name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Dependencies
        uses: ./.github/actions/setup-python

      - name: Run pre-commit
        run: uv run pre-commit run --all-files

  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Dependencies
        uses: ./.github/actions/setup-python

      - name: Run tests with pytest
        run: |
          uv run pytest

  pyright:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python and Dependencies
        uses: ./.github/actions/setup-python

      - name: Run pyright
        run: |
          uv run pyright
