from enum import StrEnum


class AgentName(StrEnum):
    APPRAISER = "APPRAISER"
    PROFILER = "PROFILER"
    RESEARCHER = "RESEARCHER"
    SENTINEL = "SENTINEL"
    STRATEGIST = "STRATEGIST"
    SURVEYOR = "SURVEYOR"
